# Example: kind create cluster --config ./kind-mgmt-cluster.yaml --name mgmt
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/lib/docker
        containerPath: /var/lib/docker
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: tcp
      - containerPort: 30443
        hostPort: 30443
        protocol: tcp
