apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 30080
      targetPort: 30080
      nodePort: 30080 # Set in the kind cluster config
      protocol: TCP
    - name: https
      port: 30443
      targetPort: 30443
      nodePort: 30443 # Set in the kind cluster config
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx

---
