apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-loki
  namespace: dashboards
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
  loki.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "loki",
                "orgId": 1,
                "type": "loki",
                "url": "http://loki.logging.svc:3100",
                "version": 1
            }
        ]
    }